---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-dcbot
  namespace: algo-dcbot
  labels:
    app: algo-dcbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algo-dcbot
  template:
    metadata:
      labels:
        app: algo-dcbot
    spec:
      containers:
      - name: dcbot
        image: gitea.konchin.com/service/algo-dcbot:latest
        env:
          - name: DC_TOKEN
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: DC_TOKEN
          - name: DC_CLIENTID
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: DC_CLIENTID
          - name: ADMIN_ID
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: ADMIN_ID
          - name: DEFAULT_ROLE
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: DEFAULT_ROLE
      imagePullSecrets:
      - name: regcred
