---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-dcbot
  namespace: algo-dcbot
  labels:
    app: algo-dcbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algo-dcbot
      rel: stable
  template:
    metadata:
      labels:
        app: algo-dcbot
        rel: stable
        ver: '0.3'
    spec:
      containers:
      - name: dcbot
        image: 'gitea.konchin.com/services/algo-dcbot:latest'
        env:
          - name: DC_TOKEN
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: dcbot-token
          - name: DC_CLIENTID
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: dcbot-id
          - name: ADMIN_ID
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: maintainer-id
          - name: DEFAULT_ROLE
            valueFrom:
              secretKeyRef:
                name: algo-dcbot-secret
                key: default-role-id
      imagePullSecrets:
      - name: regcred
